included:
  - Sources
  - Tests
  - Examples

excluded:
  - .build
  - .derivedData
  - Examples/DiaryApp/.derivedData
  - Examples/DiaryApp/.derivedData/**

disabled_rules:
  - static_over_final_class

opt_in_rules:
  - explicit_init
  - force_unwrapping

line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true

identifier_name:
  min_length: 2
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - x
    - y

type_name:
  min_length: 3
  max_length:
    warning: 60
    error: 80

type_body_length:
  warning: 350
  error: 500

file_length:
  warning: 600
  error: 900
